
name: Daily Price Monitor

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 4 AM UTC (adjust to your time zone if necessary)
  workflow_dispatch:     # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          GOOGLE_SHEET_CREDS: ${{ secrets.GOOGLE_SHEET_CREDS }}  # If needed for Sheets
        run: |
          python monitor_price.py
# name: Daily Price Monitor

# on:
#   schedule:
#     - cron: '0 4 * * *'  # Runs daily at 4 AM UTC
#   workflow_dispatch:     # Allows manual run

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run monitor script
#         env:
#           DB_HOST: ${{ secrets.DB_HOST }}
#           DB_PORT: ${{ secrets.DB_PORT }}
#           DB_USER: ${{ secrets.DB_USER }}
#           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#           DB_NAME: ${{ secrets.DB_NAME }}
#         run: |
#           python monitor_price.py


